### ISSUE TITLE
懶人包 & 活動細節

### ISSUE THREAD

**Issue by zbryikt** [g0v/g0v-grant-landing#2]
懶人包與活動細節怎麼辦？
* 懶人包 - 做幾張圖說明？
* 活動細節 - 直接給 google docs ?

**Comment by aelcenganda** [comment]
建議不要叫做活動細節，下載「獎助金申請細則」
活動細則直接給google doc review版，或是給pdf 連結？

**Comment by clkao** [comment]
we have the pdf!
