### ISSUE TITLE
網站首圖文字

### ISSUE THREAD

**Issue by aelcenganda** [g0v/g0v-grant-landing#9]
有沒有 g0v ，有沒有 prototype?
>	g0v 公民科技創新獎助金	
>	g0v Civic Tech Grant

須確定 Slogan
> 沒有人要給你錢！

3. 副標
> 公民科技 += 總金額 300 萬 x 6 個月
2017.1.1-2.10 公民黑客提案++

1. 中英文名稱要確定。中文裡要有 g0v 嗎？英文裡要有 prototype 嗎？
2. 我用總金額放在這裡宣傳，因為30-50萬實在是太拗口難看了

**Comment by ipaaa** [comment]
請用子龍新排的把 g0v 排入公民科技獎助金的版本吧～

**Comment by aelcenganda** [comment]
![2016-12-13 14 39 48](https://cloud.githubusercontent.com/assets/9480974/21130270/3fcfd41c-c142-11e6-86ac-a7ee05ce233f.png)

**Comment by zbryikt** [comment]
updated as discussion ( as in grant Landing page final checklist )
use svg for better layout
